In [1]:
import numpy as np

In [8]:
minha_lista = [20,30,10]

## convertendo minha lista do python nativo para um array do numpy

In [5]:
lista = np.array(minha_lista)

In [6]:
print (lista)

[20 30 10]


In [7]:
type(lista)

numpy.ndarray

## criando um array com bidimensional usando a list, ou seja, uma matriz. 

In [15]:
list = np.array([[20,30,10,],[52,66,99],[44,66,88]])
list

array([[20, 30, 10],
       [52, 66, 99],
       [44, 66, 88]])

## usando o arenge para criar uma sequencia no array com (inicio, fim, parametro)

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## atribuindo zeros no array bidimensional 

In [21]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## atribuindo 1 no array bidimensional 

In [35]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
line = 2 * np.ones((3,3))
line

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

## matriz identidade 

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## linspace requer um início e fim de números, 
## além da especificação da quantidade de números igualmente espaçados que deseja gerar

In [37]:
np.linspace(0,100,20) 

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

## o random.rand é uma função para gerar numeros aleatorios de 0 a 1 usando números aleatórios distribuídos uniformemente

In [83]:
np.random.rand(10)

array([0.04029152, 0.01366439, 0.47710301, 0.11038158, 0.2271584 ,
       0.24521244, 0.33503759, 0.31524313, 0.70717674, 0.33246391])

## o random.randn é uma função para gerar numeros aleatorios de 0 a 1 usando o metodo gaussiano 

In [39]:
np.random.randn(5)

array([-1.02227696,  0.95761661, -1.60528361,  0.39224476, -1.38516363])

## a função random.randint vai escolher numeros aleatorios de um tamnho informado, 
## por exemplo de 0 a 99 e vai preencher a matriz 5x5

In [86]:
np.random.randint(100, size = (5,5) )

array([[64, 38, 65, 72, 21],
       [29, 13, 36, 90, 99],
       [90, 13, 65, 35, 62],
       [92, 90, 52, 22, 80],
       [ 8, 61, 82, 70, 80]])

In [49]:
arr2 = np.random.rand(50)
arr2

array([0.84155973, 0.75108891, 0.5113724 , 0.6846688 , 0.54780866,
       0.78445982, 0.00971072, 0.01036177, 0.13698855, 0.49277844,
       0.43674143, 0.97485175, 0.6631948 , 0.63233722, 0.8671568 ,
       0.88178305, 0.799083  , 0.27899466, 0.94378428, 0.38962889,
       0.64814256, 0.19909341, 0.51884181, 0.88281031, 0.88022813,
       0.22951591, 0.84572328, 0.06484502, 0.19215873, 0.93435977,
       0.56333571, 0.16769622, 0.87143382, 0.63186935, 0.30333554,
       0.33151318, 0.2286883 , 0.60066241, 0.12357273, 0.28502645,
       0.16862262, 0.63406194, 0.85566511, 0.54866093, 0.40551546,
       0.38254177, 0.03977413, 0.45350744, 0.10021236, 0.20128037])

## reshape muuda o array de uma dimensao para qualquer dimensao. 

In [75]:
array5 = np.arange(24)
array5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [80]:
array5.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## extrações de array para um sub array

In [89]:
num = np.arange(0,80,5)
num

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [93]:
num[5]


25

In [92]:
num[:5]

array([ 0,  5, 10, 15, 20])

In [97]:
num[4:5] = 200
num

array([  0,   5,  10,  15, 200,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75])

num2 = np.arange(60).reshape((6,10))
num2

## atraves de uma array num2 eu criei outa matriz colocando os parametros que eu quero. e eu ultilizei o 

In [109]:
num3 = num2[0:3][0:8].copy()
num3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

## foi definido bol sendo qualquer numero do num3 maior que 10
## e então inseri bol para pegar somento os numeros maiores que 10

In [113]:
bol = num3 > 10
num3[bol]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

## aqui é possivel multiplicar array bidimensionais por outros array, porem te que ter o mesmo tamanho.

In [114]:
num2 + num2

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118]])

In [120]:
num2 **2

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401],
       [2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481]])

In [115]:
num2 - num2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [116]:
num2/num2 

C:\Users\leona\AppData\Local\Temp\ipykernel_9752\2383294106.py:1: RuntimeWarning: invalid value encountered in divide
  num2/num2


array([[nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

## usando as funções de raiz, exponencial, media, minimo, maximo etc 

In [122]:
np.sqrt(num2) 

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481],
       [5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
        5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ],
       [6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
        6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ],
       [7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
        7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575]])

In [123]:
np.exp(num2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
        6.56599691e+07, 1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
        2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
        1.44625706e+12, 3.93133430e+12],
       [1.06864746e+13, 2.90488497e+13, 7.89629602e+13, 2.14643580e+14,
        5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16],
       [2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
        1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
        7.01673591e+20, 1.90734657e+21],
       [5.18470553e+21, 1.40934908e+22, 3.83100800e+22, 1.04137594e+23,
   

In [124]:
np.mean(num2)

29.5

In [125]:
np.max(num2)

59

In [126]:
np.min(num2)

0